name: NopCommerce Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium Pytest tests
      run: pytest --html=report.html --self-contained-html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: Test Report
        path: report.html
